services:
  backend:
    container_name: workflowBackend
    image: ${DOCKERHUB_USERNAME}/workflow-backend:latest
    build: 
      context: .
      dockerfile: dockerfile.node
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - .:/app

  database:
    container_name: workflowDB
    image: ${DOCKERHUB_USERNAME}/workflow-database:latest
    build: 
      context: .
      dockerfile: dockerfile.mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: